include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - flutter_sdk/**
    - flutter_sdk_new/**
    - build/**
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
